/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/89ee1a82-6706-4969-9a54-eb4a0145cb38 
  Arduino IoT Cloud Variables description
  The following variables are automatically generated and updated when changes are made to the Thing

  CloudIlluminance intensity;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
# define value 700 
float bhsensor;
#include <Arduino.h>
#include <hp_BH1750.h>
hp_BH1750 BH1750;


void setup() {
  Serial.begin(9600);
  // delay
  delay(1500); 
  pinMode(LED_BUILTIN, OUTPUT);
  
  bool available = BH1750.begin(BH1750_TO_GROUND);
  
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  BH1750.start();   
  bhsensor = BH1750.getLux();
  intensity = bhsensor;
  if(intensity > value)
  {
    Serial.println("Sunlight is hitting the terrarium");
    digitalWrite(LED_BUILTIN, HIGH);
    delay(1000);
    digitalWrite(LED_BUILTIN, LOW);
    delay(1000);
  }
 
}

void onIntensityChange()  {
  // Add your code here to act upon Intensity change
}
